<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<div class="left"><?php _e("Seven Framework") ?><br><?php echo Seven::version(true); ?></div>
<div class="right"><?php _e("All rights are reserved") ?><br>Copyright &copy; <?php echo date("Y"); ?></div>
<?php if($this->getItems()) : ?>
<div class="center">
    <?php $is_first = true; ?>
    <?php foreach($this->getItems() as $item) : ?>
        <?php if(!$is_first) : ?>|<?php endif; ?>
        <a href="<?php echo $item->hasHref() ? $item->getHref() : $this->getUrl($item->getUrl()); ?>"><?php echo $item->getLabel(); ?></a>
        <?php $is_first = false; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>

