<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<?php if(!count($items = $this->getItems())) return; ?>
<ul>
    <?php foreach($items as $item) : ?>
    	<?php if(!$item->isAllowed()) continue; ?>
        <?php
            $classes = array();
            if($item->getActive()) $classes[] = 'hovered';
            if(!$this->getLevel()) $classes[] = 'top-level';
        ?>
        <li<?php if(count($classes)) echo " class='" . implode(" ", $classes) . "'" ?>>
            <?php if(count($item->getChildren())) : ?>
                <div class="label"><?php echo $item->getLabel(); ?></div>
                <?php echo $this->toHtmlMenu($item); ?>
            <?php else : ?>
                <a href="<?php echo $item->getHref(); ?>"><?php echo $item->getLabel(); ?></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

