<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<li <?php echo $this->getAttributeString(); ?>>
	<?php if(count($this->getChildren())) : ?>
		<div class="label"><?php echo $this->getLabel(); ?></div>
		<?php echo $this->getParent()->toHtmlMenu($this); ?>
	<?php else : ?>
		<a href="<?php echo $this->getHref(); ?>"><?php echo $this->getLabel(); ?></a>
	<?php endif; ?>
</li>
