<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Admin
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<h2><?php _e('Package details'); ?></h2>
<?php if($this->getPackage()) : ?>
<ul>
	<?php foreach($this->getPackage()->getData() as $key => $value) : ?>
	<li><b><?php echo $key; ?></b>: <?php echo is_array($value) ? var_export($value, true) : htmlspecialchars($value); ?></li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>