<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script id="infowindow-template" type="text/x-jquery-tmpl">
    {{if $data.title }}
        Школа: <b>${title}</b><br/>
        Город: <b>${city}</b><br/>
        Рейтинг: <b>${rate}</b><br/>
        ID: <b>${id}</b><br/>
    {{/if}}
    <a href="<?php echo seven_url('*/*/view') ?>?id=${id} ">Детали</a>
</script>
<div id="map-info"></div>
<div id="map_canvas"></div>