<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    News
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<?php foreach($this->getCollection() as $news) : ?>
<div class="news">
	<h2><?php echo $news->getTitle(); ?></h2>
	<p><?php echo $news->getAnnounce(); ?></p>
</div>
<?php endforeach; ?>
<?php if($this->getFilter('pager')) echo $this->getFilter('pager')->toHtml(); ?>