<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<title><?php echo $this->getTitle(); ?> </title>
<?php if($this->hasFavicon()) : ?>
<link rel="icon" type="image/png" href="<?php echo $this->getFavicon(); ?>">
<?php endif; ?>
<?php foreach ($this->_getItem('css') as $name):?>
<link rel="stylesheet" href="<?php echo $name ?>" type="text/css">
<?php endforeach; ?>
<?php foreach ($this->_getItem('metahttp') as $name=>$content):?>
<meta http-equiv="<?php echo $name ?>" content="<?php echo $content; ?>">
<?php endforeach; ?>
<?php foreach ($this->_getItem('meta') as $name=>$content):?>
<meta name="<?php echo $name ?>" content="<?php echo $content; ?>">
<?php endforeach; ?>
<?php foreach ($this->_getItem('js') as $name):?>
<script type="text/javascript" src="<?php echo $name ?>"></script>
<?php endforeach; ?>
<script type="text/javascript">
	app         = new Seven.App();
	app.url     = new Seven.Url(<?php echo json_encode(Seven::app()->getRequest()->getPublicData()); ?>);
	app.i18n    = new Seven.I18n();
	app.website = new Seven.Website(<?php echo json_encode(Seven::app()->getWebsite()->getPublicData()); ?>);
</script>