<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<?php foreach(array('info', 'success', 'warning', 'error') as $type) : ?><?php if($this->getMessages($type)): ?><div id ="<?php echo $type; ?>-notifications"><ul><?php foreach($this->getMessages($type) as $message): ?><li><?php echo $message . " "; ?></li><?php endforeach; ?></ul></div><?php endif; ?><?php endforeach; ?>