<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<div class="logo">
   <?php $logo = Seven::getModel('core/image')->load(Seven::getSiteConfig("general/design/logo")); ?>
   <?php if($logo->_getId()): ?><img src="<?php echo $logo->getThumbUrl(48, 48); ?>" width="48px" height="48px" alt="<?php echo Seven::getSiteConfig("general/design/logo_alt") ?>"><?php endif; ?>
   Seven<span class='blue'>Framework</span>
</div>