<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<?php if($this->getItems()) : ?>
<ul>
    <?php foreach($this->getItemsTree() as $item) : ?>
    	<?php if(!$item->isAllowed()) continue; ?>
        <li<?php if($item->getActive()) echo " class='hovered'" ?>><a href="<?php echo $item->getHref(); ?>"><?php echo $item->getLabel(); ?></a></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>