<script id="school-item-template" type="text/x-jquery-tmpl" xmlns="http://www.w3.org/1999/html">
<li class="school-line clearfix">
	<div class="header">
        <div class="rate">
            <div class="inline">
                <span class="ratio">${rate}</span>
            </div>
        </div>
		<div class="info left">
            <h4 class="title"><a href="#">${name}</a></h4>
            <p class="address"><a href="#">${address}</a></p>
        </div>
        <div class="charts left">
            <dl>

                {{each waysChart}}
                    <dt>${name}</dt>
                    <dd title="${rate}" >
                        <div class="${color}" style="width:${width}%;"><strong></strong></div>
                    </dd>
                {{/each}}
<!--                <dt>точные</dt>-->
<!--                <dd>-->
<!--                    <div class="green" style="width:80%;"><strong></strong></div>-->
<!--                </dd>-->
<!--                <dt>гуманитарные</dt>-->
<!--                <dd>-->
<!--                    <div class="red" style="width:25%;"><strong></strong></div>-->
<!--                </dd>-->
<!--                <dt>естественные</dt>-->
<!--                <dd>-->
<!--                    <div class="yellow" style="width:55%;"><strong></strong></div>-->
<!--                </dd>-->
            </dl>
        </div>
        <div class="btnHolder left">
            <a href="#" class="btn inline close"></a>
        </div>
        <div class="additional-information">
            <div class="description">{{html description}}</div>
        </div>

    </div>
</li>
</script>
<script id="school-empty-line-template" type="text/x-jquery-tmpl">
	<li class="school-empty-line">
		<p>No campaigns found</p>
	</li>
</script>
<div class="filters">
    <ul class="clearfix">
        <?php echo $this->getFilter('radius')->getFilterHtml(); ?>
        <?php echo $this->getFilter('way')->getFilterHtml(); ?>
        <?php echo $this->getFilter('year')->getFilterHtml(); ?>
    </ul>
</div>
<div class="school-list grid">
	<div class="school-list-header">
		<div class="clear"></div>
	</div>
	<ul id="school-list"><?php echo $this->getInnerHtml(); ?></ul>
</div>
