<script id="school-item-template" type="text/x-jquery-tmpl" xmlns="http://www.w3.org/1999/html">
<li class="school-line clearfix">
	<div class="header">
        <div class="rate">
            <div class="inline">
                <span class="ratio">${rate}</span>
            </div>
        </div>
		<div class="info left">
            <h4 class="title"><a href="#">${name}</a></h4>
            <p class="address"><a href="#">${address}</a></p>
        </div>
        <div class="charts left"><span style="color:#888888">some chrats</span></div>
        <div class="btnHolder left"><a href="#" class="btn inline"></a></div>
        <div class="additional-information">
            <p class="description">${description}</p>
        </div>

    </div>
</li>
</script>
<script id="school-empty-line-template" type="text/x-jquery-tmpl">
	<li class="school-empty-line">
		<p>No campaigns found</p>
	</li>
</script>
<div class="filters">
    <ul class="clearfix">
        <?php echo $this->getFilter('radius')->getFilterHtml(); ?>
        <?php echo $this->getFilter('way')->getFilterHtml(); ?>
        <?php echo $this->getFilter('year')->getFilterHtml(); ?>
    </ul>
</div>
<div class="school-list grid">
	<div class="school-list-header">
		<div class="clear"></div>
	</div>
	<ul id="school-list"><?php echo $this->getInnerHtml(); ?></ul>
</div>
