<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<div class="widget-container">
    <?php if($this->getTitle()) : ?>
        <h1><?php echo $this->getTitle(); ?></h1>
    <?php endif; ?>
    <?php if($this->getButtons() && ($this->getButtonsTop() || $this->getButtonsTop() === null)) : ?>
        <div class="widget-container-buttons">
            <?php foreach($this->getButtons() as $button) if(!$button->getBottomOnly()) : ?> <?php echo $button->toHtml(); ?> <?php endif; ?>
        </div>
    <?php endif; ?>
    <div class="widget-container-content">
        <?php echo $this->getSortedChildrenHtml(); ?>
    </div>
    <?php if($this->getButtons() && $this->getButtonsBottom()) : ?>
        <div class="widget-container-buttons-bottom">
            <?php foreach($this->getButtons() as $button) if(!$button->getTopOnly()) : ?> <?php echo $button->toHtml(); ?> <?php endif; ?>
        </div>
    <?php endif; ?>
</div>