<div style="text-align: center">
    <h2><?php echo __('EDUMETER - ВІКРИТИЙ РЕЙТИНГ ШКІЛ ЗА РЕЗУЛЬТАТАМИ ЗНО') ?></h2>
</div>
<div class="home-dummytext">
    <?php echo $this->getChildHtml('welcome') ?>

</div>
<div class="clear"></div>

<div id="like-buttons">
    <div class="fb-like" data-send="false" data-layout="button_count" data-width="120" data-show-faces="false" data-font="lucida grande"></div>
<!--    <div id="vk_like"></div>-->
<!--    <script type="text/javascript">-->
<!--        VK.Widgets.Like("vk_like", {type: "button"});-->
<!--    </script>-->
    <div id="mailru-like">
        <a target="_blank" class="mrc__plugin_uber_like_button" href="http://connect.mail.ru/share" data-mrc-config="{'cm' : '1', 'ck' : '3', 'sz' : '20', 'st' : '2', 'tp' : 'combo'}">Нравится</a>
        <script src="http://cdn.connect.mail.ru/js/loader.js" type="text/javascript" charset="UTF-8"></script>
    </div>
    <div class="g-plusone" data-annotation="inline" data-width="120"></div>
</div>
<div class="clear"></div>
<script type="text/javascript">
    window.___gcfg = {lang: 'ru'};

    (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script>