<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<p class="text-404"><?php _e("Sorry, but you are looking for not found") ?></p>
<div class="image-404"><img  src="<?php echo $this->getSkinUrl('images/404.png')?>" alt="404page"/></div>
<h1 class="page-not-found">Page not found</h1>
