<div id="user-voice" class="rotate-90-deg">
    <a href="#user-voice-form" role="button" class="btn btn-warning" data-toggle="modal"  data-backdrop="static" keyboard="false">Сообщите об ошибке</a>
</div>

<div id="user-voice-form" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="user-voice-modal" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="user-voice-modal">Сообщить об ошибке</h3>
    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Закрыть</button>
        <button id="submit-user-voice" class="btn btn-success">Отправить</button>
    </div>
</div>