<li class="deliveryTypes fGroup" id="radius-filter">
    <ul>
        <li class="filter" id="raius-filter-500"><a href="javascript:school_list.changeRadius(500)">рядом (500 м)</a><span class="arrow"></span></li>
        <li class="filter" id="raius-filter-1000"><a href="javascript:school_list.changeRadius(1000)">пройтись (1 км)</a><span class="arrow"></span></li>
        <li class="filter" id="raius-filter-3000"><a href="javascript:school_list.changeRadius(3000)">транспортом (3 км)</a><span class="arrow"></span></li>
    </ul>
</li>

