<li class="deliveryTypes fGroup" id="radius-filter">
    <ul>
        <li class="filter" id="raius-filter-500"><a href="javascript:school_list.changeRadius(500)">рядом</a><span class="arrow"></span></li>
        <li class="filter" id="raius-filter-1000"><a href="javascript:school_list.changeRadius(1000)">пройтись</a><span class="arrow"></span></li>
        <li class="filter" id="raius-filter-5000"><a href="javascript:school_list.changeRadius(5000)">транспортом</a><span class="arrow"></span></li>
    </ul>
</li>

