<li class="schoolTypes fGroup" id="way-filter">
    <ul>
        <li class="filter" id="way-filter-global">
            <a href="javascript:school_list.changeWay('global')">все шкалы</a>
            <span class="arrow"></span>
        </li>
        <li class="filter" id="way-filter-math" >
            <a href="javascript:school_list.changeWay('math')">физико-математические</a>
            <span class="arrow"></span>
        </li>
        <li class="filter"  id="way-filter-arts">
            <a href="javascript:school_list.changeWay('arts')">гуманитарные</a>
            <span class="arrow"></span>
        </li>
        <li class="filter"  id="way-filter-natural">
            <a href="javascript:school_list.changeWay('natural')">естествознательные</a>
            <span class="arrow"></span>
        </li>
    </ul>
</li>
