<li class="schoolTypes fGroup">
    <ul>
        <li class="filter">
            <a href="#">все шкалы</a>
            <span class="arrow"></span>
        </li>
        <li class="filter active">
            <a href="#">физико-математические</a>
            <span class="arrow"></span>
        </li>
        <li class="filter">
            <a href="#">гуманитарные</a>
            <span class="arrow"></span>
        </li>
        <li class="filter">
            <a href="#">естествознательные</a>
            <span class="arrow"></span>
        </li>
    </ul>
</li>
