<li class="yearType fGroup" id="year-filter">
    <ul>
        <li class="filter" id="year-filter-2008">
            <a href="javascript:school_list.changeYear(2008)">с 2008 год</a>
            <span class="arrow"></span>
        <li class="filter" id="year-filter-2012">
            <a href="javascript:school_list.changeYear(2012)">последний год</a>
            <span class="arrow"></span>
        </li>
    </ul>
</li>
