<li class="separatorType fGroup">|</li>
<li class="yearType fGroup" id="year-filter">
    <ul>
        <li class="filter" id="year-filter-2010">
            <a href="javascript:school_list.changeYear(2010, true)">с 2010</a>
            <span class="arrow"></span>
        </li>
        <li class="filter" id="year-filter-2012">
            <a href="javascript:school_list.changeYear(2012 , false)">последний</a>
            <span class="arrow"></span>
        </li>
    </ul>
</li>
