<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<div class="widget-box">
    <h2>System info</h2>
    <b>Seven version:</b> <?php echo Seven::version(true); ?><br>
    <b>Environment type:</b> <?php echo Seven::app()->isDeveloperMode() ? "Developement" : "Production"; ?><br>
    <b>PHP version:</b> <?php echo phpversion(); ?><br>
    <b>Server:</b> <?php echo $_SERVER['SERVER_SOFTWARE']; ?><br>
</div>