<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<?php if(count($this->getChildren()) > 1) : ?>
<div class ="widget-tabs">
    <ul class ="widget-tabs-list">
        <?php foreach($this->getSortedChildren() as $name => $child):?>
        <li><a class ="" href ="#<?php echo $child->getHtmlId(); ?>"> <?php echo $child->getLabel() ?></a></li>
        <?php endforeach; ?>
    </ul>
    <div class="widget-tabs-holder">    
        <?php foreach($this->getSortedChildren() as $name => $child):?>
            <div id ="<?php echo $child->getHtmlId(); ?>"> <?php echo $child->toHtml()  ?> </div>
        <?php endforeach; ?>
    </div>
</div>
<?php else : ?>
    <?php echo $this->getChildrenHtml(); ?>
<?php endif; ?>
