<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>


<footer class="clearfix">
    <div class="centered">
        <div class="logo left"><img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="Edimeter logo" /></div>
        <div class="links right">
            <ul class="left">
                <?php if($this->getItems()) : ?>
                    <?php foreach($this->getItems() as $item) : ?>
                        <li>
                            <a href="<?php echo $item->hasHref() ? $item->getHref() : $this->getUrl($item->getUrl()); ?>"><?php echo $item->getLabel(); ?></a>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
            <div class="copyright left">
                <span>All rights reserved (c)</span>
            </div>
        </div>
    </div>
</footer>