<footer class="clearfix">
    <div class="centered">
        <div class="logo left"><a href="/"><img src="<?php echo $this->getSkinUrl("images/logo.png");?>" alt="Edumeter"></a></div>
        <div class="links right">
            <ul class="left">
                <li><a href="#">О нас</a></li>
                <li><a href="#">Вопросы</a></li>
                <li><a href="#">Условия предоставления услуг</a></li>
                <li><a href="#">Контакты </a></li>
            </ul>
            <div class="copyright left">
                <span>(c) Ilya Voinov</span>
            </div>
        </div>
    </div>
</footer>