<header>
    <div class="centered clearfix">
        <div class="logo left">
            <a href="/"><img src="<?php echo $this->getSkinUrl("images/logo.png");?>" alt="Edumeter"></a>
        </div>
        <div class="siteMenu right">
            <p class="left"><a href="#">Как это работает</a></p>
            <div class="searchWrap left">
                <form class="formSearch">
                    <input type="text" class="txtSearch inline">
                    <a href="#" class="btnClear"></a>
                </form>
            </div>
            <p class="left"><a href="/">Глобальный рейтинг школ</a></p>
        </div>
    </div>
</header>