<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<header class="clearfix">
    <div class="centered clearfix">
        <div class="logo left">
            <img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="Edimeter logo" />

        </div>
        <div class="description left">
            <span> рейтинг школ Украины по результатам ВНО</span>
        </div>
        <div class="siteMenu right">
            <div class="searchWrap left">
                <form class="formSearch" method="post" onsubmit="return map.search($('#searchAddressValue').val())" >
                    <input id="searchAddressValue" name ="searchAddressValue" type="text" class="txtSearch inline" placeholder="Введите свой адрес"/>
                </form>
            </div>
        </div>
    </div>
</header>