<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<input type='file' <?php echo $this->getAttributeString(); ?>>
<?php if($this->getFile() && $this->getFile()->_getId()) : ?>
<div class="widget-input-file">
    <div class="widget-input-file-prop">
        <ul>
            <li><b><?php _e("Name") ?>:</b> <?php echo basename($this->getFile()->getPath()); ?></li>
            <li><b><?php _e("Size") ?>:</b> <?php echo $this->getFile()->getSize(); ?> <?php _e("bytes") ?></li>
        </ul>
    </div>
    <div class="widget-input-file-delete">
        <label><input name="<?php echo $this->getHtmlName() ?>_delete" <?php echo $this->getDeleteFile() ? "checked" : ""; ?> type="checkbox"> <?php _e("Delete") ?></label>
    </div>
    <div class="widget-input-file-download">
        <a href="<?php echo $this->getFile(); ?>"><?php _e("Download"); ?></a>
    </div>
</div>
<?php endif; ?>
