<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Seven
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<div <?php echo $this->getAttributeString(); ?>>
	<?php echo $this->getInnerHtml(); ?>
</div>
<script>
	var grid_<?php echo $this->getHtmlId(); ?> = new Seven.WidgetGrid(<?php echo json_encode(array_intersect_key($this->getData(), array('use_ajax' => '', 'ajax_url' => '', 'html_id' => ''))); ?>); 
</script>
