<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Seven
 * @package    Access
 * @author     Sergey Kolodyazhnyy <sergey.kolodyazhnyy@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 *
 */
?>
<label><?php echo $this->getInputHtml(); ?> <?php echo $this->getName() ?: $this->getTreePath(); ?></label>
<?php if($this->getChildren()) : ?>
<ul>
<?php foreach($this->getChildren() as $name => $child) : ?>
	<li><?php echo $child->toHtml(); ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
